/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharesRouteImport } from './routes/shares'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivateRouteImport } from './routes/private'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ListRouteImport } from './routes/_list'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListUnreviewedRouteImport } from './routes/_list/unreviewed'
import { Route as ListTodosRouteImport } from './routes/_list/todos'
import { Route as ListStaleRouteImport } from './routes/_list/stale'
import { Route as ListRecentRouteImport } from './routes/_list/recent'
import { Route as ListNotesRouteImport } from './routes/_list/notes'
import { Route as ListAttentionRouteImport } from './routes/_list/attention'
import { Route as ListArchivedRouteImport } from './routes/_list/archived'
import { Route as ListAllRouteImport } from './routes/_list/all'
import { Route as ListTodosIndexRouteImport } from './routes/_list/todos/index'
import { Route as ListScratchIndexRouteImport } from './routes/_list/scratch/index'
import { Route as ListNotesIndexRouteImport } from './routes/_list/notes/index'
import { Route as ListTodosDoneRouteImport } from './routes/_list/todos/done'
import { Route as ListNotesPermanentRouteImport } from './routes/_list/notes/permanent'
import { Route as ListNotesFleetingRouteImport } from './routes/_list/notes/fleeting'
import { Route as ListNotesExportedRouteImport } from './routes/_list/notes/exported'
import { Route as ListNotesDevelopingRouteImport } from './routes/_list/notes/developing'

const SharesRoute = SharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/_list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListUnreviewedRoute = ListUnreviewedRouteImport.update({
  id: '/unreviewed',
  path: '/unreviewed',
  getParentRoute: () => ListRoute,
} as any)
const ListTodosRoute = ListTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => ListRoute,
} as any)
const ListStaleRoute = ListStaleRouteImport.update({
  id: '/stale',
  path: '/stale',
  getParentRoute: () => ListRoute,
} as any)
const ListRecentRoute = ListRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => ListRoute,
} as any)
const ListNotesRoute = ListNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ListRoute,
} as any)
const ListAttentionRoute = ListAttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => ListRoute,
} as any)
const ListArchivedRoute = ListArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => ListRoute,
} as any)
const ListAllRoute = ListAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ListRoute,
} as any)
const ListTodosIndexRoute = ListTodosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListTodosRoute,
} as any)
const ListScratchIndexRoute = ListScratchIndexRouteImport.update({
  id: '/scratch/',
  path: '/scratch/',
  getParentRoute: () => ListRoute,
} as any)
const ListNotesIndexRoute = ListNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListNotesRoute,
} as any)
const ListTodosDoneRoute = ListTodosDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => ListTodosRoute,
} as any)
const ListNotesPermanentRoute = ListNotesPermanentRouteImport.update({
  id: '/permanent',
  path: '/permanent',
  getParentRoute: () => ListNotesRoute,
} as any)
const ListNotesFleetingRoute = ListNotesFleetingRouteImport.update({
  id: '/fleeting',
  path: '/fleeting',
  getParentRoute: () => ListNotesRoute,
} as any)
const ListNotesExportedRoute = ListNotesExportedRouteImport.update({
  id: '/exported',
  path: '/exported',
  getParentRoute: () => ListNotesRoute,
} as any)
const ListNotesDevelopingRoute = ListNotesDevelopingRouteImport.update({
  id: '/developing',
  path: '/developing',
  getParentRoute: () => ListNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/private': typeof PrivateRoute
  '/settings': typeof SettingsRoute
  '/shares': typeof SharesRoute
  '/all': typeof ListAllRoute
  '/archived': typeof ListArchivedRoute
  '/attention': typeof ListAttentionRoute
  '/notes': typeof ListNotesRouteWithChildren
  '/recent': typeof ListRecentRoute
  '/stale': typeof ListStaleRoute
  '/todos': typeof ListTodosRouteWithChildren
  '/unreviewed': typeof ListUnreviewedRoute
  '/notes/developing': typeof ListNotesDevelopingRoute
  '/notes/exported': typeof ListNotesExportedRoute
  '/notes/fleeting': typeof ListNotesFleetingRoute
  '/notes/permanent': typeof ListNotesPermanentRoute
  '/todos/done': typeof ListTodosDoneRoute
  '/notes/': typeof ListNotesIndexRoute
  '/scratch/': typeof ListScratchIndexRoute
  '/todos/': typeof ListTodosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/private': typeof PrivateRoute
  '/settings': typeof SettingsRoute
  '/shares': typeof SharesRoute
  '/all': typeof ListAllRoute
  '/archived': typeof ListArchivedRoute
  '/attention': typeof ListAttentionRoute
  '/recent': typeof ListRecentRoute
  '/stale': typeof ListStaleRoute
  '/unreviewed': typeof ListUnreviewedRoute
  '/notes/developing': typeof ListNotesDevelopingRoute
  '/notes/exported': typeof ListNotesExportedRoute
  '/notes/fleeting': typeof ListNotesFleetingRoute
  '/notes/permanent': typeof ListNotesPermanentRoute
  '/todos/done': typeof ListTodosDoneRoute
  '/notes': typeof ListNotesIndexRoute
  '/scratch': typeof ListScratchIndexRoute
  '/todos': typeof ListTodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_list': typeof ListRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/private': typeof PrivateRoute
  '/settings': typeof SettingsRoute
  '/shares': typeof SharesRoute
  '/_list/all': typeof ListAllRoute
  '/_list/archived': typeof ListArchivedRoute
  '/_list/attention': typeof ListAttentionRoute
  '/_list/notes': typeof ListNotesRouteWithChildren
  '/_list/recent': typeof ListRecentRoute
  '/_list/stale': typeof ListStaleRoute
  '/_list/todos': typeof ListTodosRouteWithChildren
  '/_list/unreviewed': typeof ListUnreviewedRoute
  '/_list/notes/developing': typeof ListNotesDevelopingRoute
  '/_list/notes/exported': typeof ListNotesExportedRoute
  '/_list/notes/fleeting': typeof ListNotesFleetingRoute
  '/_list/notes/permanent': typeof ListNotesPermanentRoute
  '/_list/todos/done': typeof ListTodosDoneRoute
  '/_list/notes/': typeof ListNotesIndexRoute
  '/_list/scratch/': typeof ListScratchIndexRoute
  '/_list/todos/': typeof ListTodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/private'
    | '/settings'
    | '/shares'
    | '/all'
    | '/archived'
    | '/attention'
    | '/notes'
    | '/recent'
    | '/stale'
    | '/todos'
    | '/unreviewed'
    | '/notes/developing'
    | '/notes/exported'
    | '/notes/fleeting'
    | '/notes/permanent'
    | '/todos/done'
    | '/notes/'
    | '/scratch/'
    | '/todos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/private'
    | '/settings'
    | '/shares'
    | '/all'
    | '/archived'
    | '/attention'
    | '/recent'
    | '/stale'
    | '/unreviewed'
    | '/notes/developing'
    | '/notes/exported'
    | '/notes/fleeting'
    | '/notes/permanent'
    | '/todos/done'
    | '/notes'
    | '/scratch'
    | '/todos'
  id:
    | '__root__'
    | '/'
    | '/_list'
    | '/dashboard'
    | '/private'
    | '/settings'
    | '/shares'
    | '/_list/all'
    | '/_list/archived'
    | '/_list/attention'
    | '/_list/notes'
    | '/_list/recent'
    | '/_list/stale'
    | '/_list/todos'
    | '/_list/unreviewed'
    | '/_list/notes/developing'
    | '/_list/notes/exported'
    | '/_list/notes/fleeting'
    | '/_list/notes/permanent'
    | '/_list/todos/done'
    | '/_list/notes/'
    | '/_list/scratch/'
    | '/_list/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListRoute: typeof ListRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  PrivateRoute: typeof PrivateRoute
  SettingsRoute: typeof SettingsRoute
  SharesRoute: typeof SharesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shares': {
      id: '/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof SharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_list': {
      id: '/_list'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_list/unreviewed': {
      id: '/_list/unreviewed'
      path: '/unreviewed'
      fullPath: '/unreviewed'
      preLoaderRoute: typeof ListUnreviewedRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/todos': {
      id: '/_list/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof ListTodosRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/stale': {
      id: '/_list/stale'
      path: '/stale'
      fullPath: '/stale'
      preLoaderRoute: typeof ListStaleRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/recent': {
      id: '/_list/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof ListRecentRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/notes': {
      id: '/_list/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof ListNotesRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/attention': {
      id: '/_list/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof ListAttentionRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/archived': {
      id: '/_list/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ListArchivedRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/all': {
      id: '/_list/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof ListAllRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/todos/': {
      id: '/_list/todos/'
      path: '/'
      fullPath: '/todos/'
      preLoaderRoute: typeof ListTodosIndexRouteImport
      parentRoute: typeof ListTodosRoute
    }
    '/_list/scratch/': {
      id: '/_list/scratch/'
      path: '/scratch'
      fullPath: '/scratch/'
      preLoaderRoute: typeof ListScratchIndexRouteImport
      parentRoute: typeof ListRoute
    }
    '/_list/notes/': {
      id: '/_list/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof ListNotesIndexRouteImport
      parentRoute: typeof ListNotesRoute
    }
    '/_list/todos/done': {
      id: '/_list/todos/done'
      path: '/done'
      fullPath: '/todos/done'
      preLoaderRoute: typeof ListTodosDoneRouteImport
      parentRoute: typeof ListTodosRoute
    }
    '/_list/notes/permanent': {
      id: '/_list/notes/permanent'
      path: '/permanent'
      fullPath: '/notes/permanent'
      preLoaderRoute: typeof ListNotesPermanentRouteImport
      parentRoute: typeof ListNotesRoute
    }
    '/_list/notes/fleeting': {
      id: '/_list/notes/fleeting'
      path: '/fleeting'
      fullPath: '/notes/fleeting'
      preLoaderRoute: typeof ListNotesFleetingRouteImport
      parentRoute: typeof ListNotesRoute
    }
    '/_list/notes/exported': {
      id: '/_list/notes/exported'
      path: '/exported'
      fullPath: '/notes/exported'
      preLoaderRoute: typeof ListNotesExportedRouteImport
      parentRoute: typeof ListNotesRoute
    }
    '/_list/notes/developing': {
      id: '/_list/notes/developing'
      path: '/developing'
      fullPath: '/notes/developing'
      preLoaderRoute: typeof ListNotesDevelopingRouteImport
      parentRoute: typeof ListNotesRoute
    }
  }
}

interface ListNotesRouteChildren {
  ListNotesDevelopingRoute: typeof ListNotesDevelopingRoute
  ListNotesExportedRoute: typeof ListNotesExportedRoute
  ListNotesFleetingRoute: typeof ListNotesFleetingRoute
  ListNotesPermanentRoute: typeof ListNotesPermanentRoute
  ListNotesIndexRoute: typeof ListNotesIndexRoute
}

const ListNotesRouteChildren: ListNotesRouteChildren = {
  ListNotesDevelopingRoute: ListNotesDevelopingRoute,
  ListNotesExportedRoute: ListNotesExportedRoute,
  ListNotesFleetingRoute: ListNotesFleetingRoute,
  ListNotesPermanentRoute: ListNotesPermanentRoute,
  ListNotesIndexRoute: ListNotesIndexRoute,
}

const ListNotesRouteWithChildren = ListNotesRoute._addFileChildren(
  ListNotesRouteChildren,
)

interface ListTodosRouteChildren {
  ListTodosDoneRoute: typeof ListTodosDoneRoute
  ListTodosIndexRoute: typeof ListTodosIndexRoute
}

const ListTodosRouteChildren: ListTodosRouteChildren = {
  ListTodosDoneRoute: ListTodosDoneRoute,
  ListTodosIndexRoute: ListTodosIndexRoute,
}

const ListTodosRouteWithChildren = ListTodosRoute._addFileChildren(
  ListTodosRouteChildren,
)

interface ListRouteChildren {
  ListAllRoute: typeof ListAllRoute
  ListArchivedRoute: typeof ListArchivedRoute
  ListAttentionRoute: typeof ListAttentionRoute
  ListNotesRoute: typeof ListNotesRouteWithChildren
  ListRecentRoute: typeof ListRecentRoute
  ListStaleRoute: typeof ListStaleRoute
  ListTodosRoute: typeof ListTodosRouteWithChildren
  ListUnreviewedRoute: typeof ListUnreviewedRoute
  ListScratchIndexRoute: typeof ListScratchIndexRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListAllRoute: ListAllRoute,
  ListArchivedRoute: ListArchivedRoute,
  ListAttentionRoute: ListAttentionRoute,
  ListNotesRoute: ListNotesRouteWithChildren,
  ListRecentRoute: ListRecentRoute,
  ListStaleRoute: ListStaleRoute,
  ListTodosRoute: ListTodosRouteWithChildren,
  ListUnreviewedRoute: ListUnreviewedRoute,
  ListScratchIndexRoute: ListScratchIndexRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListRoute: ListRouteWithChildren,
  DashboardRoute: DashboardRoute,
  PrivateRoute: PrivateRoute,
  SettingsRoute: SettingsRoute,
  SharesRoute: SharesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
